name = "bizinfotest"
main = "src/index.js"
compatibility_date = "2024-04-19"

[[d1_databases]]
binding = "DB"
database_name = "policy-funding-db-test"
database_id = "bd4cc5b2-b877-4a1f-845f-71390825ab64"
